services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker server:app --bind 0.0.0.0:10000"
    plan: free