services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand:|
      apt-get update
      apt-get install -y ffmpeg nodejs
      pip install -U yt-dlp
      pip install -r requirements.txt
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker server:app --bind 0.0.0.0:10000"

    plan: free
